# Generated by Django 4.1.3 on 2022-12-03 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatdraw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatnames',
            name='hat_names_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hattasks',
            name='hat_tasks_text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='HatTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hat_task_text', models.CharField(max_length=400)),
                ('hat_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatdraw.hattasks')),
            ],
        ),
        migrations.CreateModel(
            name='HatName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hat_name_text', models.CharField(max_length=100)),
                ('hat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatdraw.hatnames')),
            ],
        ),
    ]
