# Generated by Django 4.1.3 on 2022-12-03 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatdraw', '0002_alter_hatnames_hat_names_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100)),
                ('hat_names_text', models.TextField()),
                ('hat_tasks_text', models.TextField()),
                ('task_discard', models.BooleanField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hatname',
            name='hat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatdraw.hat'),
        ),
        migrations.AlterField(
            model_name='hattask',
            name='hat_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatdraw.hat'),
        ),
        migrations.DeleteModel(
            name='HatNames',
        ),
        migrations.DeleteModel(
            name='HatTasks',
        ),
    ]
